# Use a lightweight Linux image with the GCC compiler installed
FROM gcc:latest

# Create a working directory inside the container
WORKDIR /usr/src/app

# We will mount the user's code here dynamically, so we don't need to COPY anything yet.